<?php

$students = array(

    "anderson" => array(
        "project_title" => "To be Changed",
        "full_name" => "Palmer Anderson",
        "hometown" => "Madison, CT",
        "concentration" => "BFA (Motion Design and Animation)",
        "campus" => "Storrs",
        "advisor" => "Heejoo Kim",
        "medium" => "3D Animation",
        "running_time" => "2 min",
        "links" => NULL,
        "statement" => "Space Film: Episode I - Retaliation of the Dark Side is a sci-fi stop motion animation that shows the struggle between good and evil using action figures from my favorite movie franchise Star Wars.  This short film is a love letter to the series that filled my imagination growing up while also being a showcase of both my 3D motion and editing skills.  Due to some very unfortunate circumstances, almost all of my first semesters progress on a digital animation I was working on for my senior project titled Taz and the Three Gems was lost and unable to be recovered.  However, I decided to completely redraft my project and make something in the little time I had that I can truly say I am passionate about.  I hope you enjoy watching it as much as I did making it come to life.  ",
        "bio" => "Palmer Anderson is a Senior Digital Media and Design major at University of Connecticut with a concentration in motion design and animation.  His family and friends are the two most important aspects of his life.  Sci-fi, videogames, and movies all have a special place in his heart and Palmer can be often found drawing, listening to or playing music, and spinning around lightsabers thinking it makes him look cool.  Since a very young age, Palmer has been inspired by animation in series such as Dragon Ball Z which forged his desire to be part of a team that makes digital content to motivate a new generation of aspiring creative professionals. ",
        "student_websites" => array("https://www.linkedin.com/in/palmer-anderson/"),
        "img_files" => NULL,
        "vimeo_urls" => array("410402366")
    ),

    "bagley" => array(
        "project_title" => "Unwavering",
        "full_name" => "Hannah Bagley",
        "hometown" => "Mystic, CT",
        "concentration" => "BFA (Game Design)",
        "campus" => "Storrs",
        "advisor" => "James Coltrain",
        "medium" => "Video Game",
        "running_time" => NULL,
        "links" => array("https://hannahbagley.myportfolio.com/"),
        "statement" => "Attending University has been an extraordinary experience for me. Total freedom awaited me at every moment, as long as what I wanted to do did not require a vehicle. My boyfriend could say the same in some regard. We hit things off early in our junior year. We were (and are) head over heels every day for each other. It was not until a month later that certain differences outside of our control began to rise to the surface. Cultural pushbacks, self-doubts, and more plagued our thoughts and attitudes. Our relationship was seen as an impossibility by outside forces within our families. We were adamant, though. Hence the title of my game, Unwavering, demonstrates the unwavering love the two player characters (one character now for time's sake) have for each other, and how they refuse to give up on what they have. This game is both a vent piece for myself as well as a comfort piece for others my age who face the same or similar dilemmas. Romeo and Juliet-esque stories have existed for centuries, but their presence in the video game medium is incredibly slim. The game-like elements are more limited due to this title being more narrative-driven, but I made sure to make the project an enjoyable interactive experience regardless. I wanted to explore these themes of love and adversity with a dash of overcoming mental struggles. These mental struggles manifest as shadowy illusions that try to slow the player down in their already doubt-filled journey. ",
        "bio" => "Mystic-based Hannah Bagley has been surrounded by video games since kindergarten. It was a new form of play that transcended the physical boundaries of her house. Being inspired by the virtual worlds she has spent thousands of hours in across her childhood, she knew from an early age that designing games would be a dream job. Video games have always been a much more engaging piece of media to her as opposed to books or movies. They provided fun interactivity and a sandbox of endless possibilities. Upon discovering the Digital Game Design concentration at the University of Connecticut, Hannah went from an unshakable disdain for extra schooling to being enthusiastic about finally diving deeper into the field she desperately wanted to be a part of. Alongside completing her senior project Unwavering, she is currently helping develop a strategy title called Bounce Castle with the Connecticut-based indie studio Robot Monkey Brain.",
        "student_websites" => array("https://hannahbagley.myportfolio.com/"),
        "social_media_links" => "https://www.linkedin.com/in/hannah-bagley-81bb4b1b9/ ",
        "img_files" => NULL,
        "vimeo_urls" => array("410402366")
    ),
    "beaman" => array(
        "project_title" => "RACE INSTINCT",
        "full_name" => "Evan Beaman",
        "hometown" => "New Hartford, CT",
        "concentration" => "BFA (Digital Film/Video Production)",
        "campus" => "Storrs",
        "advisor" => "Busra Coduroglu",
        "medium" => "Narrative Short Film",
        "running_time" => "15 min",
        "links" => "https://www.evanbeaman.com/videography/raceinstinctpilot",
        "statement" => "Based loosely on true events, RACE INSTINCT is a cinematic dive into the adrenaline-fueled subculture of street racing through the lens of the protagonist, Miles Brockman. Miles, a reserved car enthusiast, battles with traumatic instances in his past that hold him back from challenging himself to improve past racing his stopwatch. This pilot episode introduces characters like Jack and Axel, embodying the contrasting facets of the street racing community—friendship, rivalry, and the unspoken bonds forged in the pursuit of speed.",
        "bio" => "Evan Beaman is pursuing a BFA in Digital Media Design with a concentration in Film/Video Production at the University of Connecticut. As an aspiring filmmaker, Evan has years of expertise in camera & gimbal operation,  and is proficient in Adobe Premiere Pro & Davinci Resolve. It all started as a hobby for Evan, capturing friend and family moments on a cheap DSLR camera. Now he's moving on to more substantially relevant work, focusing on topics that interest him nonetheless, but have an audience that is more than just himself. From freelance client work to evolving his own brand, Evan never ceases to find a project to put his passion towards. He  wishes to evoke from his audience the same feelings he experiences while creating his short films.",
        "student_websites" => array("https://evanbeaman.com/"),
        "social_media_links" => array("https://youtube.com/@raceinstinct", "https://instagram.com/evandbeaman"),
        "img_files" => NULL,
        "vimeo_urls" => array("410402366")
    ),
    "Bologna" => array(
        "project_title" => "Bothersome",
        "full_name" => "Shay Albert",
        "hometown" => "Greenwich, CT",
        "concentration" => "BFA (3D Animation)",
        "campus" => "Storrs",
        "advisor" => "Dennis Recchia",
        "medium" => "3D animation",
        "running_time" => "2-3 minutes",
        "links" => NULL,
        "statement" => NULL,
        "bio" => "Robin Bologna is a student of the University of Connecticut pursuing a major in Digital Media and Design with a concentration in 3D Animation and a dual degree in English. Storytelling in forms such as dance, music, writing, and art have always been a passion of hers. Along with her already existing love for movies, her history in dance and art influenced her fascination in 3D animation due to the in depth work with movement. Using skills from both majors such as animation, modeling, lighting, creative writing, and general design, she hopes to get a job that will allow her to tell stories that will help make people happy or escape somewhere else just as all her favorite stories do for her.",
        "student_websites" => NULL,
        "social_media_links" => NULL,
        "img_files" => NULL,
        "vimeo_urls" => array("410402366")
    ),
    "Bresmon" => array(
        "project_title" => "Numi the Goblin Girl",
        "full_name" => "Samantha Bresmon",
        "hometown" => "Bethel, CT",
        "concentration" => "BFA (Motion Design & Animation)",
        "campus" => "Stamford",
        "advisor" => "Samantha Olschan",
        "medium" => "2D Animation",
        "running_time" => "3 min 43 sec",
        "links" => NULL,
        "statement" => "Numi the Goblin Girl is a story that first originated in my freshman year of college for an assignment to create a fake show pitch.  The idea stayed in my head and developed over the years until I decided to bring it to life.  The pilot episode starts with Numi and her little brother Iggi bored up in the attic.  They decide to sneak their friend Alex out of summer school, only they run into more trouble than they were prepared for.  The pilot takes place in the middle of the character’s story, throwing the viewer straight into their world.  The goal for my project was to build the foundation for a comforting and fun show that draws people into the fantastical world of Numi the Goblin Girl.",
        "bio" => "Samantha Bresmon is a Digital Media Design major with a concentration in Motion Design and Animation at UConn Stamford.  She focuses her talents in character illustration, story development, and combined 2D and 3D animation.  She has always been interested in expressing herself creatively and found that animation was the perfect outlet.  What started out as a love for playing pretend and crayon drawings of cartoon faces turned into a dream to create art, stories, and animations to share with the world.",
        "student_websites" => NULL,
        "social_media_links" => NULL,
        "img_files" => NULL,
        "vimeo_urls" => array("410402366")
    ),
    "Chan" => array(
        "project_title" => "Apple’s Law",
        "full_name" => "Jason Chan",
        "hometown" => "West Hartford, CT",
        "concentration" => "BFA (Motion Design & Animation)",
        "campus" => "Storrs",
        "advisor" => "Anna Lindemann",
        "medium" => "2D animation",
        "running_time" => "1 min 30 sec",
        "links" => "https://www.apples-law.com/",
        "statement" => "Apple's Law orchestrates a visual symphony, challenging viewers to reflect on the universal language of symbolism. This animation weaves together myth, history, and contemporary culture, blurring physical boundaries and inviting audiences to reconsider the enduring significance of the apple in human experience. The whimsical narrative serves as an exploration of knowledge, temptation, and innovation, encouraging viewers to contemplate the interconnected threads of our collective consciousness.",
        "bio" => "Jason Chan is a senior at the University of Connecticut, majoring in Digital Media Design with a concentration in Motion Design & Animation and a minor in Industrial Design. He enjoys creating an entertaining digital experience for an audience through humorous and profound means. Jason has worked on various projects, including animations, CAD fashion design, and UI design. He collaborated on the animation 'Climate Change: A Call to Action,' which won an Honorable Mention in the One Earth Young Filmmakers Contest. He has also collaborated with the Bushnell Performing Arts Center and the Jake Kulak Band, for the Bushnell’s Local Arts Stage and the Multi-Channel Video Installation class. He has recorded numerous videos for the UConn student television, UCTV.",
        "student_websites" => NULL,
        "social_media_links" => NULL,
        "img_files" => NULL,
        "vimeo_urls" => array("410402366")
    ),
    "Cioffi" => array(
        "project_title" => "The GM’s Revenge",
        "full_name" => "Nick Cioffi",
        "hometown" => "Trumbull, CT",
        "concentration" => "BFA (3D Animation)",
        "campus" => "Storrs",
        "advisor" => "Dennis Recchia",
        "medium" => "3D animation",
        "running_time" => "About 3 min",
        "links" => "https://portfolio.adobe.com/ab1641d6-d17c-467d-9e73-7f5d5e1b9250/editor/",
        "statement" => "The GM's Grudge is a short film about being noticed. Sometimes we work jobs where we feel invisible or under appreciated, this film is about showing people just how important and influencial you really are.
 ",
        "bio" => "Nick Cioffi is a person who is obsessed with stories. He has been consuming digital content since he can remember and he dreams to oneday hold some influence over his digital world. He has taken up 3D animation to one day do just that.
 ",
        "student_websites" => "https://portfolio.adobe.com/ab1641d6-d17c-467d-9e73-7f5d5e1b9250/editor/title-pending",
        "social_media_links" => array("https://www.linkedin.com/in/nick-cioffi-918431233/"),
        "img_files" => NULL,
        "vimeo_urls" => array("410402366")
    ),
    "Comunale" => array(
        "project_title" => "Fishtopher",
        "full_name" => "Kasimir Comunale",
        "hometown" => "New Haven, CT",
        "concentration" => "BFA (Motion Design and Animation)",
        "campus" => "Stamford",
        "advisor" => "Steven Harper",
        "medium" => "2D animation",
        "running_time" => "Around 3 min",
        "links" => "http://kasimircomunale.art/",
        "statement" => "Fishtopher, is a pilot episode for an animated series that explores the challenges of its socially anxious titular character, Fishtopher, as they go to university and are met with a relentless group of students wanting him to join their band. Using a wide range of animation techniques, this use of different approaches to filming/designing will help the viewing audience understand Fishtophers emotions throughout the pilot.",
        "bio" => "Kasimir Comunale is a trans-queer student at the University of Connecticut-Stamford aiming for their BFA in Digital Media Design with a concentration in Motion Design & Animation. Born in New Haven to a videographer father and a crafty mother, making videos and projects from a very young age has given them a keen eye for creation. Passionate about art in almost every different kind of media possible, hybrid workflows are second nature to her. Creation has been an aspect of every part of things he enjoys doing, illustration being a main part of that. Inspired by television throughout their whole life, being a part of media creation is his dream he knows will come to fruition.",
        "student_websites" => "http://www.kasimircomunale.com/",
        "social_media_links" => "https://www.instagram.com/butchoid/",
        "img_files" => NULL,
        "vimeo_urls" => array("410402366")
    ),

    "DeLima" => array(
        "project_title" => "The Princess and The Sword",
        "full_name" => "Pedro DeLima",
        "hometown" => "Danbury, CT",
        "concentration" => "BFA (Motion Design & Animation)",
        "campus" => "Stamford",
        "advisor" => "Samantha Olschan",
        "medium" => "2D animation",
        "running_time" => "3 min",
        "links" => "https://josedelima1.wixsite.com/my-sitee",
        "statement" => "The Princess and The Sword is an idea that I conceptualized back in 2018. I developed a mini pilot episode of it for my senior project. In it, a young princess named Lily faces a trial in order to prove she is worthy of wielding a magical sword passed down through her family. The project was inspired by my love of fantasy and story based cartoons, especially the ones I grew up with. I wanted to create something that would hopefully entertain people the same way the stories I grew up watching entertained and inspired me.",
        "bio" => "Pedro DeLima is an artist and animator, as well as a Motion Design and Animation student at the University of Connecticut. From a young age Pedro was enamored with animation of all forms. He grew up watching cartoons, animated movies, and playing video games. These experiences helped to grow his love for animation, ultimately leading him to choose it as his career path. ",
        "student_websites" => NULL,
        "social_media_links" => NULL,
        "img_files" => NULL,
        "vimeo_urls" => array("410402366")
    ),
    "Fahs" => array(
        "project_title" => "Ilaria",
        "full_name" => "Veronica Fahs",
        "hometown" => "Wilton, CT",
        "concentration" => "BFA (Digital Film/Video Production)",
        "campus" => "Storrs",
        "advisor" => "Brian Bliss",
        "medium" => "Narrative Short Film",
        "running_time" => "20-30min",
        "links" => "https://veronicafahs.myportfolio.com/",
        "statement" => "In 'Ilaria,' I strive to blend personal narrative with societal reflections. Through compelling visuals, the film prompts viewers to consider their actions and shared responsibilities. Set in the captivating backdrop of Southern Italy, it juxtaposes beauty with the harsh realities of the immigration crisis.
 ",
        "bio" => "Veronica Fahs is passionate about creating narrative-styled films. The roles that she enjoys pursuing in the film industry pertain to directing, screenwriting, color grading, and editing. At the University of Connecticut, the major she is studying is Digital Media and Design, concentrating on Digital Film/Video Production, consisting of working on film projects with other filmmakers, working independently on personal short films, screenwriting for upcoming projects, and creating advertisements for businesses. Veronica is intrigued by films revolving around cultural themes, social issues, and innovative stories. She is striving to pursue a career in the film industry by utilizing her passion for creating stories that spread important messages to the world.
 ",
        "student_websites" => array("https://veronicafahs113c.myportfolio.com/senior-project"),
        "social_media_links" => NULL,
        "img_files" => NULL,
        "vimeo_urls" => array("410402366")
    ),
    "Flynn" => array(
        "project_title" => "ClimbConnect",
        "full_name" => "Megan Flynn",
        "hometown" => "Chatham, NJ",
        "concentration" => "BFA (Web/Interactive Media Design)",
        "campus" => "Storrs",
        "advisor" => "Ting Zhou",
        "medium" => "Mobile App",
        "running_time" => NULL,
        "links" => NULL,
        "statement" => "ClimbConnect is a mobile app designed to help climbers find others with the same hobby. The app connects climbers with similar skill levels, schedules, and preferences. Users can post to forums, follow people and locations, connect with others, and message each other. Climbers can detail in their profiles what kinds of climbing they prefer, their grades and certifications, and more. This app aims to help people connect with the climbing community, make new friends, and encourage people to climb more- together. Certain types of climbing require more than just one person, and with the help of ClimbConnect, users can easily find others to climb with. Research shows that this type of resource would encourage people to climb more and break down barriers of entry to certain types of climbing. We believe that climbing should be accessible to all and encourage people to connect with others and engage the community.",
        "bio" => "Megan Flynn is graduating with a concentration in Web and Interactive Media Design. Her passion for user experience design stems from her love of design and her understanding of how users think and interact with digital designs. She loves creating designs based on user data and iterating with user feedback. Megan's background is in web design and programming, with an immense interest in CSS and emerging design trends and standards. Megan explores the outdoors, rock climbing, crocheting, or watching late-night television shows when she's not designing. 
 ",
        "student_websites" => array("megflynndesign.com", "https://climbconnect.myportfolio.com/"),
        "social_media_links" => NULL,
        "img_files" => NULL,
        "vimeo_urls" => array("410402366")
    ),
    "Fournier" => array(
        "project_title" => "Growing Pains",
        "full_name" => "Sydney Fournier",
        "hometown" => "South Windsor, CT",
        "concentration" => "BFA (3D Animation)",
        "campus" => "Storrs",
        "advisor" => "Dan Pejril",
        "medium" => "3D animation",
        "running_time" => "1 min 40 sec",
        "links" => NULL,
        "statement" => "Growing Pains is a 3D animated short film that explores the emotions surrounding the transition between childhood and adulthood. This transition is both comforting and uncomfortable, exciting and sad, and is one that we all experience in different ways. This story is an example of one of those personal experiences.
 ",
        "bio" => "Sydney Fournier is a 3D animation student within the Digital Media and Design program and she immensely enjoys storytelling through her work. Her approach to all projects is to create a piece of work that evokes emotion in the audience. She has worked with UConn Athletics for the past three years in roles within both the creative and video production departments, and she loves to watch her work displayed live during sporting events. After graduating, she will find a role as a 3D Motion Artist and she truly enjoys the chance to take on a new challenge.
 ",
        "student_websites" => array("https://www.sydneyfournier.com/"),
        "social_media_links" => array("https://www.linkedin.com/in/sydney-fournier2/"),
        "img_files" => NULL,
        "vimeo_urls" => array("410402366")
    ),
    "Freeman" => array(
        "project_title" => "Hockey Threads",
        "full_name" => "Matt Freeman",
        "hometown" => "Amesbury, MA",
        "concentration" => "BFA (Web/Interactive Media Design)",
        "campus" => "Storrs",
        "advisor" => "Brian Daley",
        "medium" => "Website",
        "running_time" => NULL,
        "links" => "https://xd.adobe.com/view/25850507-b24d-48c7-bbff-ed894e81f032-70d6/?fullscreen",
        "statement" => NULL,
        "bio" => NULL,
        "student_websites" => array("http://mattfreeman.myportfolio.com"),
        "social_media_links" => array("https://www.linkedin.com/in/matt-freeman-085ab7244/"),
        "img_files" => NULL,
        "vimeo_urls" => array("410402366")
    ),
    "Furano" => array(
        "project_title" => "Eyes in the Sky",
        "full_name" => "DJ Furano",
        "hometown" => "Greenwich, CT",
        "concentration" => "BFA (Digital Film/ TV Production)",
        "campus" => "Storrs",
        "advisor" => "John Murphy",
        "medium" => "Documentary Short Film",
        "running_time" => "7 min 10 sec",
        "links" => "https://djfurano.myportfolio.com/senior-project",
        "statement" => "'Eyes in the Sky'is a compelling short documentary that provides an immersive exploration of the intricacies of football coaching, shedding light on the indispensable role of coaches' film in shaping the sport. This documentary offers an exclusive behind-the-scenes glimpse into the world of football coaching, revealing the pivotal role that film analysis plays in strategizing, enhancing player performance, and ultimately, achieving triumph on the field. In the world of competitive football, success is not merely measured by touchdowns and victories; it's a culmination of dedication, strategy, and relentless commitment to improvement. 'Eyes in the Sky' takes viewers on an exhilarating journey through the lens of coaches, showcasing their tireless efforts to dissect each play, scrutinize every move, and extract insights that lead to tactical mastery.
 The documentary provides a unique perspective on how the marriage of technology and football acumen converges on the sidelines. Viewers will witness the fusion of art and science as coaches navigate the intricate web of players' strengths, weaknesses, and opponents' strategies, all guided by the watchful eyes of the camera. 'Eyes in the Sky' underscores the symbiotic relationship between coaches, players, and film analysis, revealing the hidden intricacies that define the modern game of football.",
        "bio" => "DJ Furano, a graduating artist, delves into the captivating world of football coaches' film, blending videography with a passion for sports. With a keen eye for detail, DJ Furano's senior project captures the strategic essence of the gridiron. This cinematic exploration is a testament to pushing boundaries, translating the intensity of game analysis into a visual language. Slow-motion sequences and tactical insights unfold a dynamic narrative, inviting viewers into the compelling realm of football strategy. The project serves as a canvas for cinematic experimentation, where editing techniques and storytelling converge to create an immersive experience. DJ Furano invites you to witness this fusion of passion and dedication, celebrating the journey and anticipating the continued evolution of their cinematic voice.",
        "student_websites" => array("https://djfurano.myportfolio.com/senior-project"),
        "social_media_links" => NULL,
        "img_files" => NULL,
        "vimeo_urls" => array("410402366")
    ),
    "Green" => array(
        "project_title" => "Marcy's House",
        "full_name" => "Brooklyn Green",
        "hometown" => "Vernon, CT",
        "concentration" => "BFA (Digital Film/TV Production)",
        "campus" => "Storrs",
        "advisor" => "Catherine Masud",
        "medium" => "Documentary Short Film",
        "running_time" => "13 min",
        "links" => "https://brooklyngreen.myportfolio.com/sen",
        "statement" => NULL,
        "bio" => "Over the years Brooklyn Green has always admired her mothers' dedication and independence to her salon. Marcy is a mother who has owned her hair salon in Vernon Connecticut for over 20 years now. Ever since Brooklyn was a little girl she always helped her mother in any way she could. Brooklyn wanted to show her dedication to all the work Marcy has done by making a short episode of her salon that she could use to promote her business. This would be a reality TV format of a couple of days in Marcy’s' life working in the salon. Brooklyn’s goal for this episode is for it to be inspirational and entertaining. She would love to work for a reality TV company so this would be a great way for her to further her career to a more professional level of reality TV.",
        "student_websites" => NULL,
        "social_media_links" => NULL,
        "img_files" => NULL,
        "vimeo_urls" => array("410402366")
    ),
    "Gutting" => array(
        "project_title" => "The Mysterious Box",
        "full_name" => "Alexander Gutting",
        "hometown" => "Weston, MA",
        "concentration" => "BFA (Motion Design & Animation)",
        "campus" => "Storrs",
        "advisor" => "Dan Pejril",
        "medium" => "3D animation",
        "running_time" => "2 min 54 sec",
        "links" => "https://www.alexandergutting.com/seniorproject",
        "statement" => "A boy buys an old chess set at a sidewalk sale for a dollar and goes to a chess table in the park to set up the pieces. During the game, he notices something very unusual and what happens next amazes the boy as he sees his dream come true. I learned how to play chess at a young age. When I was seven years old, I read the book Checkmate! My First Chess Book by Garry Kasparov, a Chess Grandmaster. I taught myself to play and then joined after-school clubs where I could play against others. I eventually participated in a chess tournament where I won a first-place trophy and realized how important the game of chess is to me. Chess has taught me how to focus and expanded my self-confidence and creativity. This story stems from my love of chess and my desire to create intriguing storylines. I hope The Mysterious Box evokes a feeling of wonder and connects with the audience's own passions.",
        "bio" => "Alexander Gutting is a senior at the University of Connecticut pursuing a BFA in Digital Media Design with a concentration in Motion Design and Animation. During high school, Alex developed a strong interest in creating videos and animation, and he took four semesters of video production as well as 3D motion/design classes. At UConn, he volunteers at UCTV where he records and edits high-quality film projects. During the summer of 2023, Alex worked as an intern at a medical lab equipment manufacturing company, where he helped create explainer video content for the company's website. Alex is driven by his passion for creating 2D/3D animations and motion graphics. He also enjoys filming and editing impactful projects such as mini-documentaries and producing digital music. Outside of digital media creation, Alex enjoys long-distance running, traveling, and playing chess.",
        "student_websites" => array("https://www.alexandergutting.com/"),
        "social_media_links" => array("www.linkedin.com/in/alexandergutting"),
        "img_files" => NULL,
        "vimeo_urls" => array("410402366")
    ),
    "Hitchiner" => array(
        "project_title" => "Dreamin’",
        "full_name" => "John Hitchiner",
        "hometown" => "Granby, CT",
        "concentration" => "BFA (Motion Design and Animation)",
        "campus" => "Storrs",
        "advisor" => "Dennis Recchia",
        "medium" => "2D animation",
        "running_time" => "3 min 20 sec",
        "links" => "https://johnhitchiner.wixsite.com/website/senior-project",
        "statement" => "Dreamin' is a 2D animation about a kids imagination coming alive from a bedtime story. It starts off with parents telling kids a story, and as they listen, the screen blurs and fades to the beginning of the story. 
 
 The story cuts to 2 heroes, on a mission to defeat and evil villain on top of a mountain in his evil lair. They have to go through obstacles, climb cliffsides, and fight enemies all the way up on their journey. 
 
 The story comes to a close as the heroes make it to the top of the mountain and face the evil villain in his lair. The epic boss fight will consist of a silhouette style and conclude the story, as it wraps up back to the bedroom where the story was told.",
        "bio" => "I am currently a Senior at The University of Connecticut majoring in Digital Media & Design with a Motion Design and Animation concentration. I was inspired join the DMD program at UConn because I have always had a passion for the arts and to create something original and intriguing. I specialize in digital art, 2D & 3D animation, and have experience in the UX/UI field.",
        "student_websites" => array("https://johnhitchiner.wixsite.com/website"),
        "social_media_links" => NULL,
        "img_files" => NULL,
        "vimeo_urls" => array("410402366")
    ),
    "Jimenez" => array(
        "project_title" => "UConn Go",
        "full_name" => "Yuri Jimenez",
        "hometown" => "Bridgeport, CT",
        "concentration" => "BFA (Web/Interactive Media Design)",
        "campus" => "Stamford",
        "advisor" => "John Murphy",
        "medium" => "Mobile App",
        "running_time" => NULL,
        "links" => "https://www.figma.com/proto/FsuVcIf3XN7GleXHGOZ6pG/Hiking-Trail-Sticker-Collection?type=design&node-id=143-1288&t=wsFRRcSR2MS8fPrQ-1&scaling=scale-down&page-id=143%3A813&starting-point-node-id=143%3A1283&mode=design",
        "https://yurijimenez.com/",
        "statement" => "The Outing Club (UCOC) at UConn does 'anything and everything outdoors!' They host weekly outdoor trips with activities that can be as simple as hiking and yoga to as adventurous as owl spotting and rock climbing. As one of the largest no-commitment clubs at the University with over 1,500 total and 400 active members, UCOC has to ensure that every participant has transportation, the right equipment, and the right skill/training level to participate in their activities. The first time I went to their club meeting, after it ended, I remember the room was packed with lines of students trying to arrange their ride situation, asking for register links they had missed from buried emails, and asking basic questions such as gear availability. This is when I saw an opportunity to streamline those processes for the club so that members can spend less time worrying about things like rides and gear availability, and instead focus on trip planning itself.",
        "bio" => "Yuri Jimenez enjoys hearing about what motivates people to create change within themselves and their surroundings. She finds that although many people have aspirations, it is not always easy for them to articulate exactly what they are. Yuri, as a problem solver with UX design skills, assists in bringing their visions to life so they can share, inspire, and spark action within others to pursue their passions as well. Her most cherished collaboration thus far is with InnerView, rebranding and redesigning their website to support their vision to 'bring more humanity, connection, and student-empowerment to our system of education.' Yuri also has experience working with larger organizations such as Spectrum where she contributed to developing their Chatbot for improved communication methods and customer service. Moving forward, Yuri is excited for future opportunities to empower individuals and organizations, making a positive impact on people's lives.",
        "student_websites" => array("https://yurijimenez.com/"),
        "social_media_links" => array("https://www.linkedin.com/in/yuri-jimenez/"),
        "img_files" => NULL,
        "vimeo_urls" => array("410402366")
    ),
    "Johnson" => array(
        "project_title" => "A Prayer to God",
        "full_name" => "Lexis Johnson",
        "hometown" => "Paxton, MA",
        "concentration" => "BFA (Digital Film/Video Production)",
        "campus" => "Storrs",
        "advisor" => "Justin Matley",
        "medium" => "Narrative Short Film",
        "running_time" => "2-4 min",
        "links" => "https://lexisamiljohnson11ed.myportfolio.com/senior-project",
        "statement" => "My artistic journey enchants nature in the fall time. I will embark on chapter Philippians 4 through a 2-4 minute narrative film. For creativity I am going towards captivating visuals, emotive voiceover, and a crafted soundscape to profound the message of faith, hope and joy that
 is shown in the scripture. Not only does this narrative film show dedication to producing christian based content that resonates with spiritual sensibilities of the audience but also shows a testament to my ongoing
 artistic storytelling skill set.",
        "bio" => "Lexis is getting a BFA in Digital Media Design with a concentration in film/video production at the University of Connecticut. With experience in several aspects of videography. Her versatility and motivation has led her to be able to create her own small business creating content for
 sporting events, weddings, and content for companies.",
        "student_websites" => NULL,
        "social_media_links" => NULL,
        "img_files" => NULL,
        "vimeo_urls" => array("410402366")
    ),
    "Jordao" => array(
        "project_title" => "It's Gonna Be Okay",
        "full_name" => "Matthews Jordao",
        "hometown" => "Trumbull, CT",
        "concentration" => "BFA (Digital Film/Video Production)",
        "campus" => "Storrs",
        "advisor" => "Busra Coduroglu",
        "medium" => "Narrative Short Film",
        "running_time" => "6-8 min",
        "links" => "https://matthewsj19.wixsite.com/its-gonna-be-okay-fi",
        "statement" => "In 'It's Gonna Be Okay,' viewers are immersed in the tumultuous journey of Adam, a young soul navigating the shadows of high school hallways and the turmoil of a fractured home. Plagued by relentless bullying and grappling with inner demons, Adam's daily existence feels like an unending torment against his own self-worth. However, a fateful afternoon triggers an eerie out-of-body experience, thrusting him into a surreal realm where multiple versions of himself torment him mercilessly. Amidst this turmoil, a radiant door appears, offering a fleeting escape to a serene meadow—a respite from the pain that defines his reality. Yet, tranquility is short-lived as a haunting phone call propels Adam into another reality—a somber church where he confronts his own mortality amidst silent onlookers. Desperation ensues as he seeks solace in a reflection, ultimately finding a glimmer of hope in the whispered assurance, 'It's gonna be okay.' Through Adam's journey, the film delves into themes of self-worth, resilience, and the enduring human capacity for hope in the face of despair.",
        "bio" => "Matthews Jordao is a senior at the University of Connecticut, majoring in Digital Media and Design with a concentration in Video Production and Film. With a keen focus on narrative fiction films, Matthews explores non-natural themes to captivate audiences and evoke thought-provoking emotions. Throughout his academic journey, he has honed his skills in visual storytelling and cinematic techniques, bringing his creative visions to life on screen. With aspirations to make his mark in the film and television industry, Matthews is dedicated to pursuing opportunities that will allow him to showcase his passion for storytelling and his commitment to crafting compelling narratives.",
        "student_websites" => array("https://matthewsj19.wixsite.com/portfolio"),
        "social_media_links" => NULL,
        "img_files" => NULL,
        "vimeo_urls" => array("410402366")
    ),
    "Kelly" => array(
        "project_title" => "Mouse House Maze",
        "full_name" => "Kieran Kelly",
        "hometown" => "Bernardsville, NJ",
        "concentration" => "BFA (3D Animation)",
        "campus" => "Storrs",
        "advisor" => "Dan Pejril",
        "medium" => "3D animation",
        "running_time" => "2-3 min",
        "links" => "https://kierankelly0d91.myportfolio.com",
        "statement" => NULL,
        "bio" => NULL,
        "student_websites" => NULL,
        "social_media_links" => NULL,
        "img_files" => NULL,
        "vimeo_urls" => array("410402366")
    ),
    "Kopeliovich" => array(
        "project_title" => "WHUS Radio: 100 Waves of Sound",
        "full_name" => "Jonathan Kopeliovich",
        "hometown" => "Los Angeles, CA",
        "concentration" => "BFA (Digital Film/Video Production)",
        "campus" => "Storrs",
        "advisor" => "Catherine Masud",
        "medium" => "Website",
        "running_time" => NULL,
        "links" => "https://archive.whus.org/",
        "statement" => "The WHUS Archive is an archive celebrating the 100th anniversary of the student radio at UConn. It will combine timelines of WHUS history with images, videos, zines, documents, and airchecks from the 1920s to present to present the transformation of a community radio station. 
 
 Throughout my college career, WHUS Radio has been an invigorating experience that’s allowed me to explore multimedia production and to discover my love for journalism. The variety of opportunities and freeform programming is what contributed to its longevity. I wish to capture this spirit with a rich tapestry of interviews, collages of punk-like art, and archival radio broadcasts. What also makes the radio so special to me is that in my youth, radio has influenced my music taste. Before I had an iPod or Spotify, my parents played Queen and Led Zeppelin on the classic rock stations. I grew to love punk and films like Scott Pilgrim vs. the World and Baby Driver. These influences found their way into my films like Dirty Laundry, where a student obsessively investigates the theft of his clothes in a montage set to a punk song. I will take the skills developed in making the WHUS Archive and apply them towards a career in science communication and research.
 
 Throughout my college career, WHUS Radio has been an invigorating experience that’s allowed me to explore multimedia production and to discover my love for journalism. The variety of opportunities and freeform programming is what contributed to its longevity. I wish to capture this spirit with animation, interviews, collages of punk-like art, and archival radio broadcasts. What also makes the radio so special to me is that in my youth, radio has influenced my music taste and my style of rhythmic editing and hyperactive montages. Before I had an iPod or Spotify, my parents played Queen and Led Zeppelin on the classic rock stations. I grew to love punk and films like Scott Pilgrim vs. the World and Baby Driver. These influences found their way into my films like Dirty Laundry, where a student obsessively investigates the theft of his clothes in a montage set to a punk song. I will take the skills developed in making the WHUS Archive and apply them towards a career in science communication and documentary production.",
        "bio" => "Jonathan Kopeliovich is a Los Angeles-based journalist and documentarian in the Digital Media Design program at the University of Connecticut. He is aiming for a Bachelor’s in Fine Arts with a concentration in Digital Film/Video Production.  
 
 After his dad showed him Jim Carrey comedies, Jonathan was hooked on filmmaking and finding ways to tell stories to entertain others. A stint of film community college classes during high school combined with the diverse LA art community affirmed his excitement. After he came to UConn, he was captivated by the student radio and pursued a variety of stories on topics such as addiction, neurodiversity in engineering, and environmentalism. Jonathan is constantly looking for new mediums to experiment with. He helped produce films at the university television station, wrote for the Daily Campus, and created content for WHUS.
 
 
 Jonathan has made documentaries about the Armenian Genocide, the UConn mascot Jonathan the Husky, created narrative films about the environment, and pursued journalism. He has worked for the Department of Engineering as a writer, interned at NBC as a news correspondent, and was a science communication intern at a climate change think tank in Woods Hole. He currently works as the Training Director at WHUS Radio.",
        "student_websites" => array("https://johnkopelcom.wordpress.com"),
        "social_media_links" => array("https://www.linkedin.com/in/jonathan-kopeliovich/"),
        "img_files" => NULL,
        "vimeo_urls" => array("410402366")
    ),
    "Kerr" => array(
        "project_title" => "Cosmic Journey",
        "full_name" => "Haydn Kerr",
        "hometown" => "Sydney, AUS",
        "concentration" => "BFA (Web/Interactive Media Design)",
        "campus" => "Storrs",
        "advisor" => "Brian Daley",
        "medium" => "Website",
        "running_time" => NULL,
        "links" => array("https://haydnkerr.github.io/interactive_solar_system/"),
        "statement" => "Cosmic Journey encapsulates the awe-inspiring odyssey through our solar system, tailored to captivate the curiosity of elementary to middle school-aged children. Seamlessly blending 2D and 3D elements, this interactive exhibit invites young explorers to embark on a visually enchanting voyage, delving deep into the celestial marvels that surround us. Drawing upon a fusion of animations and interactive features, Cosmic Journey serves as a captivating educational tool, offering a comprehensive understanding of planetary bodies while igniting a passion for space exploration. Through engaging quizzes tailored to each celestial neighbor, participants are empowered to unravel the mysteries of our cosmic neighborhood. At its core, Cosmic Journey represents a culmination of expertise in UI/UX design and frontend development. By leveraging these skills, the exhibit not only showcases the wonders of our solar system but also fosters an immersive learning environment, inspiring future generations to reach for the stars.",
        "bio" => "Haydn is a Front End Developer driven by a profound passion for education and a dedication to empowering younger generations. With a background in frontend development, Haydn's ultimate dream is to make a lasting impact in the EdTech industry, bridging the gap between technology and education. Through his art, Haydn creates immersive digital experiences that inspire curiosity and foster learning. Drawing upon his expertise in UI/UX design, he crafts interactive environments that captivate young minds, inviting them to embark on transformative journeys of exploration and discovery. Each project reflects Haydn's commitment to leveraging innovation to shape the future of education. His work serves as a testament to the belief that education has the power to transform lives and shape a brighter tomorrow, one curious mind at a time.",
        "student_websites" => array("http://haydnkerr.com/"),
        "social_media_links" => array("https://www.linkedin.com/in/haydn-kerr/"),
        "img_files" => array("albert_shay_01.jpg", "albert_shay_02.jpg", "albert_shay_03.jpg", "albert_shay_04.jpg", "albert_shay_05.jpg"),
        "vimeo_urls" => array("410402366")
    ),
    "Kubisek" => array(
        "project_title" => "Cardinal North",
        "full_name" => "Carlie Kubisek",
        "hometown" => "Southington, CT",
        "concentration" => "BFA (3D Animation)",
        "campus" => "Storrs",
        "advisor" => "Dan Pejril",
        "medium" => "3D animation",
        "running_time" => "1 min 5 sec",
        "links" => NULL,
        "statement" => "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.",
        "bio" => "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua...",
        "student_websites" => array("https://www.carliemkubisek.com/"),
        "social_media_links" => NULL,
        "img_files" => array("albert_shay_01.jpg", "albert_shay_02.jpg", "albert_shay_03.jpg", "albert_shay_04.jpg", "albert_shay_05.jpg"),
        "vimeo_urls" => array("410402366")
    ),
    "McGaffigan" => array(
        "project_title" => "The Guided Path",
        "full_name" => "Mary McGaffigan",
        "hometown" => "Tyngsboro, MA",
        "concentration" => "BFA (Motion Design & Animation)",
        "campus" => "Storrs",
        "advisor" => "Anna Lindemann",
        "medium" => "2D animation",
        "running_time" => "2 min 49 sec",
        "links" => NULL,
        "statement" => "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.",
        "bio" => "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua...",
        "student_websites" => array("http://www.shayalbert.com"),
        "social_media_links" => NULL,
        "img_files" => array("albert_shay_01.jpg", "albert_shay_02.jpg", "albert_shay_03.jpg", "albert_shay_04.jpg", "albert_shay_05.jpg"),
        "vimeo_urls" => array("410402366")
    ),
    "Morneau" => array(
        "project_title" => "80HD",
        "full_name" => "Marisa Morneau",
        "hometown" => "Ellington, CT",
        "concentration" => "BFA (Web/Interactive Media Design)",
        "campus" => "Storrs",
        "advisor" => "Brian Daley",
        "medium" => "Mobile App Prototype",
        "running_time" => NULL,
        "links" => NULL,
        "statement" => "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.",
        "bio" => "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua...",
        "student_websites" => array("http://www.shayalbert.com"),
        "social_media_links" => NULL,
        "img_files" => array("albert_shay_01.jpg", "albert_shay_02.jpg", "albert_shay_03.jpg", "albert_shay_04.jpg", "albert_shay_05.jpg"),
        "vimeo_urls" => array("410402366")
    ),
    "Pontore" => array(
        "project_title" => "The Maze",
        "full_name" => "Gabriel Pontore",
        "hometown" => "Newtown, CT",
        "concentration" => "BFA (3D Animation)",
        "campus" => "Storrs",
        "advisor" => "Dennis Recchia",
        "medium" => "3D animation",
        "running_time" => "3 min 58 sec",
        "links" => NULL,
        "statement" => "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.",
        "bio" => "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua...",
        "student_websites" => array("http://www.shayalbert.com"),
        "social_media_links" => NULL,
        "img_files" => array("albert_shay_01.jpg", "albert_shay_02.jpg", "albert_shay_03.jpg", "albert_shay_04.jpg", "albert_shay_05.jpg"),
        "vimeo_urls" => array("410402366")
    ),
    "Radcliffe" => array(
        "project_title" => "Testing Me",
        "full_name" => "Dante Radecliffe",
        "hometown" => "Groton, CT",
        "concentration" => "BFA (Motion Design & Animation)",
        "campus" => "Storrs",
        "advisor" => "Heejoo Kim",
        "medium" => "2D animation",
        "running_time" => "2 min",
        "links" => NULL,
        "statement" => "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.",
        "bio" => "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua...",
        "student_websites" => array("http://www.shayalbert.com"),
        "social_media_links" => NULL,
        "img_files" => array("albert_shay_01.jpg", "albert_shay_02.jpg", "albert_shay_03.jpg", "albert_shay_04.jpg", "albert_shay_05.jpg"),
        "vimeo_urls" => array("410402366")
    ),
    "Rollins" => array(
        "project_title" => "Lune and the Light",
        "full_name" => "Joy Rollins",
        "hometown" => "Storrs, CT",
        "concentration" => "BFA (Motion Design and Animation)",
        "campus" => "Storrs",
        "advisor" => "Laurel Pehmoeller",
        "medium" => "2D animation",
        "running_time" => "3 min 30 sec",
        "links" => NULL,
        "statement" => "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.",
        "bio" => "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua...",
        "student_websites" => array("http://www.shayalbert.com"),
        "social_media_links" => NULL,
        "img_files" => array("albert_shay_01.jpg", "albert_shay_02.jpg", "albert_shay_03.jpg", "albert_shay_04.jpg", "albert_shay_05.jpg"),
        "vimeo_urls" => array("410402366")
    ),
    "Ruggiero" => array(
        "project_title" => "Time Consuming",
        "full_name" => "Lauren Ruggiero",
        "hometown" => "Andover, CT",
        "concentration" => "BFA (Motion Design and Animation)",
        "campus" => "Storrs",
        "advisor" => "Anna Lindermann",
        "medium" => "2D animation",
        "running_time" => "3 min 58 sec",
        "links" => NULL,
        "statement" => "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.",
        "bio" => "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua...",
        "student_websites" => array("http://www.shayalbert.com"),
        "social_media_links" => NULL,
        "img_files" => array("albert_shay_01.jpg", "albert_shay_02.jpg", "albert_shay_03.jpg", "albert_shay_04.jpg", "albert_shay_05.jpg"),
        "vimeo_urls" => array("410402366")
    ),
    "Salazar" => array(
        "project_title" => "For Granted",
        "full_name" => "Sydney Salazar",
        "hometown" => "Ansonia, CT",
        "concentration" => "BFA (Motion Design & Animation)",
        "campus" => "Stamford",
        "advisor" => "Steve Harper",
        "medium" => "2D Animation",
        "running_time" => "1 min 30 sec",
        "links" => NULL,
        "statement" => "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.",
        "bio" => "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua...",
        "student_websites" => array("http://www.shayalbert.com"),
        "social_media_links" => NULL,
        "img_files" => array("albert_shay_01.jpg", "albert_shay_02.jpg", "albert_shay_03.jpg", "albert_shay_04.jpg", "albert_shay_05.jpg"),
        "vimeo_urls" => array("410402366")
    ),
    "Salomon" => array(
        "project_title" => "Jack of All Trades",
        "full_name" => "Sydney Salomon",
        "hometown" => "East Meadow, NY",
        "concentration" => "BFA (Motion Design & Animation)",
        "campus" => "Storrs",
        "advisor" => "Heejoo Kim",
        "medium" => "2D animation",
        "running_time" => "3 min 58 sec",
        "links" => NULL,
        "statement" => "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.",
        "bio" => "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua...",
        "student_websites" => array("http://www.shayalbert.com"),
        "social_media_links" => NULL,
        "img_files" => array("albert_shay_01.jpg", "albert_shay_02.jpg", "albert_shay_03.jpg", "albert_shay_04.jpg", "albert_shay_05.jpg"),
        "vimeo_urls" => array("410402366")
    ),
    "Santana" => array(
        "project_title" => "Wisp’s call",
        "full_name" => "Evelyn Santana",
        "hometown" => "Stratford, CT",
        "concentration" => "BFA (Motion Design & Animation)",
        "campus" => "Stamford",
        "advisor" => "Samantha Olschan",
        "medium" => "2D animation",
        "running_time" => "3 min 58 sec",
        "links" => NULL,
        "statement" => "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.",
        "bio" => "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua...",
        "student_websites" => array("http://www.shayalbert.com"),
        "social_media_links" => NULL,
        "img_files" => array("albert_shay_01.jpg", "albert_shay_02.jpg", "albert_shay_03.jpg", "albert_shay_04.jpg", "albert_shay_05.jpg"),
        "vimeo_urls" => array("410402366")
    ),
    "Shorr" => array(
        "project_title" => "The Chocoholics Guide To College Baking",
        "full_name" => "Gabriella Shorr",
        "hometown" => "East Greenwich, RI",
        "concentration" => "BFA (Web and Interactive Media Design)",
        "campus" => "Storrs",
        "advisor" => "Ting Zhou",
        "medium" => "Website",
        "running_time" => NULL,
        "links" => NULL,
        "statement" => "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.",
        "bio" => "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua...",
        "student_websites" => array("https://gabriellashorr.com/home.html"),
        "social_media_links" => NULL,
        "img_files" => array("albert_shay_01.jpg", "albert_shay_02.jpg", "albert_shay_03.jpg", "albert_shay_04.jpg", "albert_shay_05.jpg"),
        "vimeo_urls" => array("410402366")
    ),
    "Sok Hong" => array(
        "project_title" => "Love Letter",
        "full_name" => "Eun Suk Hong",
        "hometown" => "Shelton, CT",
        "concentration" => "BFA (Motion Design & Animation)",
        "campus" => "Storrs",
        "advisor" => "Heejoo Kim",
        "medium" => "2D animation",
        "running_time" => "3 min",
        "links" => NULL,
        "statement" => "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.",
        "bio" => "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua...",
        "student_websites" => array("https://www.eunsokhong.com/"),
        "social_media_links" => array("https://www.linkedin.com/in/eunsokhong/"),
        "img_files" => array("albert_shay_01.jpg", "albert_shay_02.jpg", "albert_shay_03.jpg", "albert_shay_04.jpg", "albert_shay_05.jpg"),
        "vimeo_urls" => array("410402366")
    ),
    "Suitum" => array(
        "project_title" => "A Parent-ly Knot",
        "full_name" => "Daniel Suitum",
        "hometown" => "Woodstock, CT",
        "concentration" => "BFA (Game Design)",
        "campus" => "Storrs",
        "advisor" => "James Coltrain",
        "medium" => "Video Game",
        "running_time" => NULL,
        "links" => NULL,
        "statement" => "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.",
        "bio" => "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua...",
        "student_websites" => array("dansuitum.com"),
        "social_media_links" => NULL,
        "img_files" => array("albert_shay_01.jpg", "albert_shay_02.jpg", "albert_shay_03.jpg", "albert_shay_04.jpg", "albert_shay_05.jpg"),
        "vimeo_urls" => array("410402366")
    ),
    "Tran" => array(
        "project_title" => "Baneland",
        "full_name" => "Tony Tran",
        "hometown" => "Branford, CT",
        "concentration" => "BFA (Game Design)",
        "campus" => "Storrs",
        "advisor" => "James Coltrain",
        "medium" => "Video Game",
        "running_time" => NULL,
        "links" => NULL,
        "statement" => "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.",
        "bio" => "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua...",
        "student_websites" => array("https://dandelion-tuna-4bkc.squarespace.com/config/"),
        "social_media_links" => array("https://www.linkedin.com/in/tony-tran-8ba251270/"),
        "img_files" => array("albert_shay_01.jpg", "albert_shay_02.jpg", "albert_shay_03.jpg", "albert_shay_04.jpg", "albert_shay_05.jpg"),
        "vimeo_urls" => array("410402366")
    ),
    "Tuttle" => array(
        "project_title" => "Reminiscing",
        "full_name" => "Allison Tuttle",
        "hometown" => "Killingworth, CT",
        "concentration" => "BFA (Digital Film/Video Production)",
        "campus" => "Storrs",
        "advisor" => "Heather Cassao",
        "medium" => "Documentary Short Film",
        "running_time" => "TBD",
        "links" => NULL,
        "statement" => "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.",
        "bio" => "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua...",
        "student_websites" => array("http://www.shayalbert.com"),
        "social_media_links" => NULL,
        "img_files" => array("albert_shay_01.jpg", "albert_shay_02.jpg", "albert_shay_03.jpg", "albert_shay_04.jpg", "albert_shay_05.jpg"),
        "vimeo_urls" => array("410402366")
    ),
    "Vare" => array(
        "project_title" => "Yarn Over",
        "full_name" => "Karli Vare",
        "hometown" => "Fairfield, CT",
        "concentration" => "BFA (Web/Interactive Media Design)",
        "campus" => "Storrs",
        "advisor" => "Christine Jaworski",
        "medium" => "Website",
        "running_time" => NULL,
        "links" => NULL,
        "statement" => "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.",
        "bio" => "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua...",
        "student_websites" => array("https://karlivare.com/"),
        "social_media_links" => NULL,
        "img_fiels" => array("vare_karli_yarnover_image_001_v1.jpg", "vare_karli_yarnover_image_002_v1.jpg", "vare_karli_yarnover_image_003_v1.jpg", "vare_karli_yarnover_image_004_v1.jpg", "vare_karli_yarnover_image_005_v1.jpg"),
        "vimeo_urls" => array("410402366")
    ),
    "Vdovenko" => array(
        "project_title" => "Rabbit Hole",
        "full_name" => "Anna Maria Vdovenko",
        "hometown" => "Simsbury, CT",
        "concentration" => "BFA (Motion Design & Animation)",
        "campus" => "Storrs",
        "advisor" => "Heejoo Kim",
        "medium" => "2D animation",
        "running_time" => NULL,
        "links" => NULL,
        "statement" => "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.",
        "bio" => "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua...",
        "student_websites" => array("http://www.shayalbert.com"),
        "social_media_links" => NULL,
        "img_files" => array("albert_shay_01.jpg", "albert_shay_02.jpg", "albert_shay_03.jpg", "albert_shay_04.jpg", "albert_shay_05.jpg"),
        "vimeo_urls" => array("410402366")
    ),
    "Velez" => array(
        "project_title" => "Worrybox",
        "full_name" => "Bianca Velez",
        "hometown" => "Norwalk, CT",
        "concentration" => "BFA (Web/Interactive Media Design)",
        "campus" => "Stamford",
        "advisor" => "Ting Zhou",
        "medium" => "Mobile App",
        "running_time" => NULL,
        "links" => array("https://xd.adobe.com/view/30638fdd-f6ee-4ac1-85f7-ef10ef74421a-6530/?fullscreen&hints=on", "https://www.biancavelez.com/home/worrybox"),
        "statement" => "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.",
        "bio" => "Bianca Velez is a senior at the University of Connecticut with a BFA in Digital Media Design, with a concentration in Web/Interactive Media Design. From a young age, Bianca enjoyed drawing and crafts. In middle school, she began taking technology literacy courses, and adored the software and hardware aspects of both old and modern technology. While studying mobile programming in high school, Bianca found herself taking a web interface design course after the encouragement of her professors and mentors. By the end, she had discovered a career that would combine both her love of art, technology, and storytelling: UX & UI Design. Bianca is eager to enter the world of design so she can continue expanding her knowledge in design and user philosophy, as well as apply her knack for narrative to deliver transformative user experiences.",
        "student_websites" => "http://www.biancavelez.com/",
        "social_media_links" => "https://www.linkedin.com/in/thebiancavelez",
        "img_files" => array("albert_shay_01.jpg", "albert_shay_02.jpg", "albert_shay_03.jpg", "albert_shay_04.jpg", "albert_shay_05.jpg"),
        "vimeo_urls" => NULL
    ),
    "Vivas-Nava" => array(
        "project_title" => "Reminiscent",
        "full_name" => "Christopher Vivas-Nava",
        "hometown" => "Bridgeport, CT",
        "concentration" => "BFA (Motion Design & Animation)",
        "campus" => "Stamford",
        "advisor" => "Samantha Olschan",
        "medium" => "2D animation",
        "running_time" => "3 min 58 sec",
        "links" => NULL,
        "statement" => "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.",
        "bio" => "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua...",
        "student_websites" => array("http://www.shayalbert.com"),
        "social_media_links" => NULL,
        "img_files" => array("albert_shay_01.jpg", "albert_shay_02.jpg", "albert_shay_03.jpg", "albert_shay_04.jpg", "albert_shay_05.jpg"),
        "vimeo_urls" => array("410402366")
    ),
    "Zheng" => array(
        "project_title" => "Witch and Mushkin",
        "full_name" => "Brandon Zheng",
        "hometown" => "Willimantic, CT",
        "concentration" => "BFA (3D Animation)",
        "campus" => "Storrs",
        "advisor" => "Dennis Recchia",
        "medium" => "3D animation",
        "running_time" => "2 min",
        "links" => NULL,
        "statement" => "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.",
        "bio" => "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua...",
        "student_websites" => array("https://brandon2zheng.myportfolio.com/"),
        "social_media_links" => NULL,
        "img_files" => array("albert_shay_01.jpg", "albert_shay_02.jpg", "albert_shay_03.jpg", "albert_shay_04.jpg", "albert_shay_05.jpg"),
        "vimeo_urls" => array("410402366")
    ),


    "albert" => array(
        "project_title" => "Sign",
        "full_name" => "Shay Albert",
        "hometown" => "Woodstock, CT",
        "concentration" => "BFA (3D Animation)",
        "campus" => "Storrs",
        "advisor" => "Dennis Recchia & Dan Pejril",
        "medium" => "2D animation",
        "running_time" => "3 min 58 sec",
        "links" => NULL,
        "statement" => "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.",
        "bio" => "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum..",
        "student_websites" => array("http://www.shayalbert.com"),
        "social_media_links" => NULL,
        "img_files" => array("albert_shay_01.jpg", "albert_shay_02.jpg", "albert_shay_03.jpg", "albert_shay_04.jpg", "albert_shay_05.jpg"),
        "vimeo_urls" => array("410402366")
    ),

    "bach" => array(
        "project_title" => "Music",
        "full_name" => "Sebastian Bach",
        "hometown" => "Woodstock, NY",
        "concentration" => "BFA (3D Animation)",
        "campus" => "Stamford",
        "advisor" => "Dennis Recchia & Dan Pejril",
        "medium" => "2D animation",
        "running_time" => "3 min 58 sec",
        "links" => NULL,
        "statement" => "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.",
        "bio" => "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum..",
        "student_websites" => array("http://www.shayalbert.com"),
        "social_media_links" => NULL,
        "img_files" => array("albert_shay_01.jpg", "albert_shay_02.jpg", "albert_shay_03.jpg", "albert_shay_04.jpg", "albert_shay_05.jpg"),
        "vimeo_urls" => array("410402366")
    ),

    "boyle" => array(
        "project_title" => "Out of Left Field",
        "full_name" => "Owen Boyle",
        "hometown" => "Branford, CT",
        "concentration" => "BFA (3D Animation)",
        "campus" => "Storrs",
        "advisor" => "Dennis Recchia & Dan Pejril",
        "medium" => "3D animation",
        "running_time" => "2 min 5 sec",
        "links" => NULL,
        "statement" => "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.",
        "bio" => "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.",
        "student_websites" => array("https://owentboyle.com"),
        "social_media_links" => array("https://www.instagram.com/hardboyledart/"),
        "img_files" => array("boyle_owen_01.png", "boyle_owen_02.png", "boyle_owen_03.png", "boyle_owen_04.png", "boyle_owen_05.png", "boyle_owen_06.png"),
        "vimeo_urls" => NULL
    ),

    "cesarini" => array(
        "project_title" => "Guidance",
        "full_name" => "Emily Cesarini",
        "hometown" => "Greenwich, CT",
        "concentration" => "BFA (Game Design)",
        "campus" => "Storrs",
        "advisor" => "Kenneth Thompson",
        "medium" => "3D game",
        "running_time" => NULL,
        "links" => array("https://emilycesarini.wixsite.com/models"),
        "statement" => "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.",
        "bio" => "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.",
        "student_websites" => NULL,
        "social_media_links" => array(" https://www.linkedin.com/in/emily-cesarini/"),
        "img_files" => array("cesarini_emily_01.png"),
        "vimeo_urls" => array("414583881")
    ),
)

    ?>